version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    hostname: nginx-lb
    ports:
      - 9999:9999
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

  backend-1:
    build: .
    container_name: backend-1
    hostname: backend-1
    expose:
      - '8080'
    networks:
      - backend
      - payment-processor
    environment:
      - LISTEN_ADDR=:8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '80MB'

  backend-2:
    build: .
    container_name: backend-2
    hostname: backend-2
    expose:
      - '8080'
    networks:
      - backend
      - payment-processor
    environment:
      - LISTEN_ADDR=:8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '80MB'

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true