serviceName: es_service

http:
  port: ":8080"
  paymentsPath: /payments
  summaryPath: /payments-summary
  healthPath: /health

redis:
  address: "redis:6379"

processor:
  defaultUrl: "http://payment-processor-default:8080"
  fallbackUrl: "http://payment-processor-fallback:8080"

workers: 2